import pyautogui as py
py.press("win")
py.sleep(2)
py.write("chrome")
py.sleep(1)
py.press("enter")
py.sleep(2)
py.write("SENAI americana")
py.press("enter")
py.sleep(3)
print(py.position())
py.click(217, 474, button = "left")
py.sleep(3)
print(py.position)
py.click(1524, 760, button = "left")
py.sleep(5)
py.click(228, 500, button = "left")
print(py.position)
py.write("python")
py.sleep(1)
py.press("enter")
py.vscroll(-500)
